version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["./wait-for-it.sh", "postgres:5432", "--", "./manage.py", "runserver", "0.0.0.0:80"]
    image: ayomi/django-test
    restart: unless-stopped
    ports:
      - "80:80"
    links:
      - postgres:postgres
    volumes:
      - ./src:/ayomi

  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./conf/initdb.d:/docker-entrypoint-initdb.d
      - ./postgresql:/var/lib/postgresql
    environment:
      POSTGRES_DB: ayomi
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    expose:
      - "5432"